//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SemyaDebilov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Азс.
    /// </summary>
    // *** Start programmer edit section *** (Азс CustomAttributes)

    // *** End programmer edit section *** (Азс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АзсE", new string[] {
            "Номер as \'Номер\'",
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Состояние as \'Состояние\'"})]
    [View("АзсL", new string[] {
            "Номер as \'Номер\'",
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Состояние as \'Состояние\'"})]
    public class Азс : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fНазвание;
        
        private string fАдрес;
        
        private IIS.SemyaDebilov.Состояние fСостояние;
        
        // *** Start programmer edit section *** (Азс CustomMembers)

        // *** End programmer edit section *** (Азс CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Азс.Адрес CustomAttributes)

        // *** End programmer edit section *** (Азс.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Азс.Адрес Get start)

                // *** End programmer edit section *** (Азс.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Азс.Адрес Get end)

                // *** End programmer edit section *** (Азс.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Азс.Адрес Set start)

                // *** End programmer edit section *** (Азс.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Азс.Адрес Set end)

                // *** End programmer edit section *** (Азс.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Азс.Название CustomAttributes)

        // *** End programmer edit section *** (Азс.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Азс.Название Get start)

                // *** End programmer edit section *** (Азс.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Азс.Название Get end)

                // *** End programmer edit section *** (Азс.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Азс.Название Set start)

                // *** End programmer edit section *** (Азс.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Азс.Название Set end)

                // *** End programmer edit section *** (Азс.Название Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Азс.Номер CustomAttributes)

        // *** End programmer edit section *** (Азс.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Азс.Номер Get start)

                // *** End programmer edit section *** (Азс.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Азс.Номер Get end)

                // *** End programmer edit section *** (Азс.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Азс.Номер Set start)

                // *** End programmer edit section *** (Азс.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Азс.Номер Set end)

                // *** End programmer edit section *** (Азс.Номер Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Азс.Состояние CustomAttributes)

        // *** End programmer edit section *** (Азс.Состояние CustomAttributes)
        public virtual IIS.SemyaDebilov.Состояние Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Азс.Состояние Get start)

                // *** End programmer edit section *** (Азс.Состояние Get start)
                IIS.SemyaDebilov.Состояние result = this.fСостояние;
                // *** Start programmer edit section *** (Азс.Состояние Get end)

                // *** End programmer edit section *** (Азс.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Азс.Состояние Set start)

                // *** End programmer edit section *** (Азс.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Азс.Состояние Set end)

                // *** End programmer edit section *** (Азс.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АзсE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АзсE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АзсE", typeof(IIS.SemyaDebilov.Азс));
                }
            }
            
            /// <summary>
            /// "АзсL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АзсL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АзсL", typeof(IIS.SemyaDebilov.Азс));
                }
            }
        }
    }
}
