//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SemyaDebilov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Колонка.
    /// </summary>
    // *** Start programmer edit section *** (Колонка CustomAttributes)

    // *** End programmer edit section *** (Колонка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КолонкаE", new string[] {
            "Номер as \'Номер\'",
            "состояние as \'Состояние\'"})]
    [AssociatedDetailViewAttribute("КолонкаE", "Состав", "СоставE", true, "", "Состав", true, new string[] {
            ""})]
    [View("КолонкаL", new string[] {
            "Номер as \'Номер\'",
            "состояние as \'Состояние\'"})]
    public class Колонка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.SemyaDebilov.Состояние fсостояние;
        
        private IIS.SemyaDebilov.DetailArrayOfСостав fСостав;
        
        // *** Start programmer edit section *** (Колонка CustomMembers)

        // *** End programmer edit section *** (Колонка CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Колонка.Номер CustomAttributes)

        // *** End programmer edit section *** (Колонка.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Колонка.Номер Get start)

                // *** End programmer edit section *** (Колонка.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Колонка.Номер Get end)

                // *** End programmer edit section *** (Колонка.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Колонка.Номер Set start)

                // *** End programmer edit section *** (Колонка.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Колонка.Номер Set end)

                // *** End programmer edit section *** (Колонка.Номер Set end)
            }
        }
        
        /// <summary>
        /// состояние.
        /// </summary>
        // *** Start programmer edit section *** (Колонка.состояние CustomAttributes)

        // *** End programmer edit section *** (Колонка.состояние CustomAttributes)
        public virtual IIS.SemyaDebilov.Состояние состояние
        {
            get
            {
                // *** Start programmer edit section *** (Колонка.состояние Get start)

                // *** End programmer edit section *** (Колонка.состояние Get start)
                IIS.SemyaDebilov.Состояние result = this.fсостояние;
                // *** Start programmer edit section *** (Колонка.состояние Get end)

                // *** End programmer edit section *** (Колонка.состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Колонка.состояние Set start)

                // *** End programmer edit section *** (Колонка.состояние Set start)
                this.fсостояние = value;
                // *** Start programmer edit section *** (Колонка.состояние Set end)

                // *** End programmer edit section *** (Колонка.состояние Set end)
            }
        }
        
        /// <summary>
        /// Колонка.
        /// </summary>
        // *** Start programmer edit section *** (Колонка.Состав CustomAttributes)

        // *** End programmer edit section *** (Колонка.Состав CustomAttributes)
        public virtual IIS.SemyaDebilov.DetailArrayOfСостав Состав
        {
            get
            {
                // *** Start programmer edit section *** (Колонка.Состав Get start)

                // *** End programmer edit section *** (Колонка.Состав Get start)
                if ((this.fСостав == null))
                {
                    this.fСостав = new IIS.SemyaDebilov.DetailArrayOfСостав(this);
                }
                IIS.SemyaDebilov.DetailArrayOfСостав result = this.fСостав;
                // *** Start programmer edit section *** (Колонка.Состав Get end)

                // *** End programmer edit section *** (Колонка.Состав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Колонка.Состав Set start)

                // *** End programmer edit section *** (Колонка.Состав Set start)
                this.fСостав = value;
                // *** Start programmer edit section *** (Колонка.Состав Set end)

                // *** End programmer edit section *** (Колонка.Состав Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КолонкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КолонкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КолонкаE", typeof(IIS.SemyaDebilov.Колонка));
                }
            }
            
            /// <summary>
            /// "КолонкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КолонкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КолонкаL", typeof(IIS.SemyaDebilov.Колонка));
                }
            }
        }
    }
}
