//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SemyaDebilov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пистолет.
    /// </summary>
    // *** Start programmer edit section *** (Пистолет CustomAttributes)

    // *** End programmer edit section *** (Пистолет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПистолетE", new string[] {
            "Номер as \'Номер\'",
            "состояние as \'Состояние\'",
            "Топливо as \'Топливо\'",
            "Топливо.ТипТоплива as \'Тип топлива\'"}, Hidden=new string[] {
            "Топливо.ТипТоплива"})]
    [MasterViewDefineAttribute("ПистолетE", "Топливо", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипТоплива")]
    [View("ПистолетL", new string[] {
            "Номер as \'Номер\'",
            "состояние as \'Состояние\'",
            "Топливо.ТипТоплива as \'Тип топлива\'"})]
    public class Пистолет : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.SemyaDebilov.Состояние fсостояние;
        
        private IIS.SemyaDebilov.Топливо fТопливо;
        
        // *** Start programmer edit section *** (Пистолет CustomMembers)

        // *** End programmer edit section *** (Пистолет CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Пистолет.Номер CustomAttributes)

        // *** End programmer edit section *** (Пистолет.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Пистолет.Номер Get start)

                // *** End programmer edit section *** (Пистолет.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Пистолет.Номер Get end)

                // *** End programmer edit section *** (Пистолет.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пистолет.Номер Set start)

                // *** End programmer edit section *** (Пистолет.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Пистолет.Номер Set end)

                // *** End programmer edit section *** (Пистолет.Номер Set end)
            }
        }
        
        /// <summary>
        /// состояние.
        /// </summary>
        // *** Start programmer edit section *** (Пистолет.состояние CustomAttributes)

        // *** End programmer edit section *** (Пистолет.состояние CustomAttributes)
        public virtual IIS.SemyaDebilov.Состояние состояние
        {
            get
            {
                // *** Start programmer edit section *** (Пистолет.состояние Get start)

                // *** End programmer edit section *** (Пистолет.состояние Get start)
                IIS.SemyaDebilov.Состояние result = this.fсостояние;
                // *** Start programmer edit section *** (Пистолет.состояние Get end)

                // *** End programmer edit section *** (Пистолет.состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пистолет.состояние Set start)

                // *** End programmer edit section *** (Пистолет.состояние Set start)
                this.fсостояние = value;
                // *** Start programmer edit section *** (Пистолет.состояние Set end)

                // *** End programmer edit section *** (Пистолет.состояние Set end)
            }
        }
        
        /// <summary>
        /// Пистолет.
        /// </summary>
        // *** Start programmer edit section *** (Пистолет.Топливо CustomAttributes)

        // *** End programmer edit section *** (Пистолет.Топливо CustomAttributes)
        [PropertyStorage(new string[] {
                "Топливо"})]
        [NotNull()]
        public virtual IIS.SemyaDebilov.Топливо Топливо
        {
            get
            {
                // *** Start programmer edit section *** (Пистолет.Топливо Get start)

                // *** End programmer edit section *** (Пистолет.Топливо Get start)
                IIS.SemyaDebilov.Топливо result = this.fТопливо;
                // *** Start programmer edit section *** (Пистолет.Топливо Get end)

                // *** End programmer edit section *** (Пистолет.Топливо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пистолет.Топливо Set start)

                // *** End programmer edit section *** (Пистолет.Топливо Set start)
                this.fТопливо = value;
                // *** Start programmer edit section *** (Пистолет.Топливо Set end)

                // *** End programmer edit section *** (Пистолет.Топливо Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПистолетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПистолетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПистолетE", typeof(IIS.SemyaDebilov.Пистолет));
                }
            }
            
            /// <summary>
            /// "ПистолетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПистолетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПистолетL", typeof(IIS.SemyaDebilov.Пистолет));
                }
            }
        }
    }
}
