//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SemyaDebilov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр.
    /// </summary>
    // *** Start programmer edit section *** (Регистр CustomAttributes)

    // *** End programmer edit section *** (Регистр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрE", new string[] {
            "Оплата as \'Оплата\'",
            "Оплата.Номер as \'Номер\'",
            "Резервуар as \'Резервуар\'",
            "Резервуар.Номер as \'Номер\'"}, Hidden=new string[] {
            "Оплата.Номер",
            "Резервуар.Номер"})]
    [MasterViewDefineAttribute("РегистрE", "Оплата", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("РегистрE", "Резервуар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("РегистрL", new string[] {
            "Оплата.Номер as \'Номер\'",
            "Резервуар.Номер as \'Номер\'"})]
    public class Регистр : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.SemyaDebilov.Оплата fОплата;
        
        private IIS.SemyaDebilov.Резервуар fРезервуар;
        
        // *** Start programmer edit section *** (Регистр CustomMembers)

        // *** End programmer edit section *** (Регистр CustomMembers)

        
        /// <summary>
        /// Регистр.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Оплата CustomAttributes)

        // *** End programmer edit section *** (Регистр.Оплата CustomAttributes)
        [PropertyStorage(new string[] {
                "Оплата"})]
        [NotNull()]
        public virtual IIS.SemyaDebilov.Оплата Оплата
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Оплата Get start)

                // *** End programmer edit section *** (Регистр.Оплата Get start)
                IIS.SemyaDebilov.Оплата result = this.fОплата;
                // *** Start programmer edit section *** (Регистр.Оплата Get end)

                // *** End programmer edit section *** (Регистр.Оплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Оплата Set start)

                // *** End programmer edit section *** (Регистр.Оплата Set start)
                this.fОплата = value;
                // *** Start programmer edit section *** (Регистр.Оплата Set end)

                // *** End programmer edit section *** (Регистр.Оплата Set end)
            }
        }
        
        /// <summary>
        /// Регистр.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Резервуар CustomAttributes)

        // *** End programmer edit section *** (Регистр.Резервуар CustomAttributes)
        [PropertyStorage(new string[] {
                "Резервуар"})]
        [NotNull()]
        public virtual IIS.SemyaDebilov.Резервуар Резервуар
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Резервуар Get start)

                // *** End programmer edit section *** (Регистр.Резервуар Get start)
                IIS.SemyaDebilov.Резервуар result = this.fРезервуар;
                // *** Start programmer edit section *** (Регистр.Резервуар Get end)

                // *** End programmer edit section *** (Регистр.Резервуар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Резервуар Set start)

                // *** End programmer edit section *** (Регистр.Резервуар Set start)
                this.fРезервуар = value;
                // *** Start programmer edit section *** (Регистр.Резервуар Set end)

                // *** End programmer edit section *** (Регистр.Резервуар Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрE", typeof(IIS.SemyaDebilov.Регистр));
                }
            }
            
            /// <summary>
            /// "РегистрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрL", typeof(IIS.SemyaDebilov.Регистр));
                }
            }
        }
    }
}
