//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SemyaDebilov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Резервуар.
    /// </summary>
    // *** Start programmer edit section *** (Резервуар CustomAttributes)

    // *** End programmer edit section *** (Резервуар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РезервуарE", new string[] {
            "Номер as \'Номер\'",
            "ТипТоплива as \'Тип топлива\'",
            "Обьем as \'Обьем\'"})]
    [View("РезервуарL", new string[] {
            "Номер as \'Номер\'",
            "ТипТоплива as \'Тип топлива\'",
            "Обьем as \'Обьем\'"})]
    public class Резервуар : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.SemyaDebilov.ТипТоплива fТипТоплива;
        
        private int fОбьем;
        
        // *** Start programmer edit section *** (Резервуар CustomMembers)

        // *** End programmer edit section *** (Резервуар CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.Номер CustomAttributes)

        // *** End programmer edit section *** (Резервуар.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.Номер Get start)

                // *** End programmer edit section *** (Резервуар.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Резервуар.Номер Get end)

                // *** End programmer edit section *** (Резервуар.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.Номер Set start)

                // *** End programmer edit section *** (Резервуар.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Резервуар.Номер Set end)

                // *** End programmer edit section *** (Резервуар.Номер Set end)
            }
        }
        
        /// <summary>
        /// Обьем.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.Обьем CustomAttributes)

        // *** End programmer edit section *** (Резервуар.Обьем CustomAttributes)
        public virtual int Обьем
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.Обьем Get start)

                // *** End programmer edit section *** (Резервуар.Обьем Get start)
                int result = this.fОбьем;
                // *** Start programmer edit section *** (Резервуар.Обьем Get end)

                // *** End programmer edit section *** (Резервуар.Обьем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.Обьем Set start)

                // *** End programmer edit section *** (Резервуар.Обьем Set start)
                this.fОбьем = value;
                // *** Start programmer edit section *** (Резервуар.Обьем Set end)

                // *** End programmer edit section *** (Резервуар.Обьем Set end)
            }
        }
        
        /// <summary>
        /// ТипТоплива.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.ТипТоплива CustomAttributes)

        // *** End programmer edit section *** (Резервуар.ТипТоплива CustomAttributes)
        public virtual IIS.SemyaDebilov.ТипТоплива ТипТоплива
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.ТипТоплива Get start)

                // *** End programmer edit section *** (Резервуар.ТипТоплива Get start)
                IIS.SemyaDebilov.ТипТоплива result = this.fТипТоплива;
                // *** Start programmer edit section *** (Резервуар.ТипТоплива Get end)

                // *** End programmer edit section *** (Резервуар.ТипТоплива Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.ТипТоплива Set start)

                // *** End programmer edit section *** (Резервуар.ТипТоплива Set start)
                this.fТипТоплива = value;
                // *** Start programmer edit section *** (Резервуар.ТипТоплива Set end)

                // *** End programmer edit section *** (Резервуар.ТипТоплива Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РезервуарE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РезервуарE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РезервуарE", typeof(IIS.SemyaDebilov.Резервуар));
                }
            }
            
            /// <summary>
            /// "РезервуарL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РезервуарL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РезервуарL", typeof(IIS.SemyaDebilov.Резервуар));
                }
            }
        }
    }
}
