//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SemyaDebilov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справочник цен.
    /// </summary>
    // *** Start programmer edit section *** (СправочникЦен CustomAttributes)

    // *** End programmer edit section *** (СправочникЦен CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник цен")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправочникЦенE", new string[] {
            "ТипТоплива as \'Тип топлива\'",
            "Цена as \'Цена\'"})]
    [View("СправочникЦенL", new string[] {
            "ТипТоплива as \'Тип топлива\'",
            "Цена as \'Цена\'"})]
    public class СправочникЦен : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.SemyaDebilov.ТипТоплива fТипТоплива;
        
        private double fЦена;
        
        // *** Start programmer edit section *** (СправочникЦен CustomMembers)

        // *** End programmer edit section *** (СправочникЦен CustomMembers)

        
        /// <summary>
        /// ТипТоплива.
        /// </summary>
        // *** Start programmer edit section *** (СправочникЦен.ТипТоплива CustomAttributes)

        // *** End programmer edit section *** (СправочникЦен.ТипТоплива CustomAttributes)
        public virtual IIS.SemyaDebilov.ТипТоплива ТипТоплива
        {
            get
            {
                // *** Start programmer edit section *** (СправочникЦен.ТипТоплива Get start)

                // *** End programmer edit section *** (СправочникЦен.ТипТоплива Get start)
                IIS.SemyaDebilov.ТипТоплива result = this.fТипТоплива;
                // *** Start programmer edit section *** (СправочникЦен.ТипТоплива Get end)

                // *** End programmer edit section *** (СправочникЦен.ТипТоплива Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправочникЦен.ТипТоплива Set start)

                // *** End programmer edit section *** (СправочникЦен.ТипТоплива Set start)
                this.fТипТоплива = value;
                // *** Start programmer edit section *** (СправочникЦен.ТипТоплива Set end)

                // *** End programmer edit section *** (СправочникЦен.ТипТоплива Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (СправочникЦен.Цена CustomAttributes)

        // *** End programmer edit section *** (СправочникЦен.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (СправочникЦен.Цена Get start)

                // *** End programmer edit section *** (СправочникЦен.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (СправочникЦен.Цена Get end)

                // *** End programmer edit section *** (СправочникЦен.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправочникЦен.Цена Set start)

                // *** End programmer edit section *** (СправочникЦен.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (СправочникЦен.Цена Set end)

                // *** End programmer edit section *** (СправочникЦен.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправочникЦенE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправочникЦенE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправочникЦенE", typeof(IIS.SemyaDebilov.СправочникЦен));
                }
            }
            
            /// <summary>
            /// "СправочникЦенL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправочникЦенL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправочникЦенL", typeof(IIS.SemyaDebilov.СправочникЦен));
                }
            }
        }
    }
}
