//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SemyaDebilov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип топлива.
    /// </summary>
    // *** Start programmer edit section *** (ТипТоплива CustomAttributes)

    // *** End programmer edit section *** (ТипТоплива CustomAttributes)
    public enum ТипТоплива
    {
        
        // *** Start programmer edit section *** (ТипТоплива.1 CustomAttributes)

        // *** End programmer edit section *** (ТипТоплива.1 CustomAttributes)
        [Caption("92")]
        1,
        
        // *** Start programmer edit section *** (ТипТоплива.2 CustomAttributes)

        // *** End programmer edit section *** (ТипТоплива.2 CustomAttributes)
        [Caption("95")]
        2,
        
        // *** Start programmer edit section *** (ТипТоплива.3 CustomAttributes)

        // *** End programmer edit section *** (ТипТоплива.3 CustomAttributes)
        [Caption("98")]
        3,
        
        // *** Start programmer edit section *** (ТипТоплива.4 CustomAttributes)

        // *** End programmer edit section *** (ТипТоплива.4 CustomAttributes)
        [Caption("Дизель")]
        4,
    }
}
