//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SemyaDebilov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Топливо.
    /// </summary>
    // *** Start programmer edit section *** (Топливо CustomAttributes)

    // *** End programmer edit section *** (Топливо CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТопливоE", new string[] {
            "ТипТоплива as \'Тип топлива\'",
            "СправочникЦен as \'Справочник цен\'",
            "СправочникЦен.ТипТоплива as \'Тип топлива\'"}, Hidden=new string[] {
            "СправочникЦен.ТипТоплива"})]
    [MasterViewDefineAttribute("ТопливоE", "СправочникЦен", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипТоплива")]
    [View("ТопливоL", new string[] {
            "ТипТоплива as \'Тип топлива\'",
            "СправочникЦен.ТипТоплива as \'Тип топлива\'"})]
    public class Топливо : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.SemyaDebilov.ТипТоплива fТипТоплива;
        
        private IIS.SemyaDebilov.СправочникЦен fСправочникЦен;
        
        // *** Start programmer edit section *** (Топливо CustomMembers)

        // *** End programmer edit section *** (Топливо CustomMembers)

        
        /// <summary>
        /// ТипТоплива.
        /// </summary>
        // *** Start programmer edit section *** (Топливо.ТипТоплива CustomAttributes)

        // *** End programmer edit section *** (Топливо.ТипТоплива CustomAttributes)
        public virtual IIS.SemyaDebilov.ТипТоплива ТипТоплива
        {
            get
            {
                // *** Start programmer edit section *** (Топливо.ТипТоплива Get start)

                // *** End programmer edit section *** (Топливо.ТипТоплива Get start)
                IIS.SemyaDebilov.ТипТоплива result = this.fТипТоплива;
                // *** Start programmer edit section *** (Топливо.ТипТоплива Get end)

                // *** End programmer edit section *** (Топливо.ТипТоплива Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Топливо.ТипТоплива Set start)

                // *** End programmer edit section *** (Топливо.ТипТоплива Set start)
                this.fТипТоплива = value;
                // *** Start programmer edit section *** (Топливо.ТипТоплива Set end)

                // *** End programmer edit section *** (Топливо.ТипТоплива Set end)
            }
        }
        
        /// <summary>
        /// Топливо.
        /// </summary>
        // *** Start programmer edit section *** (Топливо.СправочникЦен CustomAttributes)

        // *** End programmer edit section *** (Топливо.СправочникЦен CustomAttributes)
        [PropertyStorage(new string[] {
                "СправочникЦен"})]
        [NotNull()]
        public virtual IIS.SemyaDebilov.СправочникЦен СправочникЦен
        {
            get
            {
                // *** Start programmer edit section *** (Топливо.СправочникЦен Get start)

                // *** End programmer edit section *** (Топливо.СправочникЦен Get start)
                IIS.SemyaDebilov.СправочникЦен result = this.fСправочникЦен;
                // *** Start programmer edit section *** (Топливо.СправочникЦен Get end)

                // *** End programmer edit section *** (Топливо.СправочникЦен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Топливо.СправочникЦен Set start)

                // *** End programmer edit section *** (Топливо.СправочникЦен Set start)
                this.fСправочникЦен = value;
                // *** Start programmer edit section *** (Топливо.СправочникЦен Set end)

                // *** End programmer edit section *** (Топливо.СправочникЦен Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТопливоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТопливоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТопливоE", typeof(IIS.SemyaDebilov.Топливо));
                }
            }
            
            /// <summary>
            /// "ТопливоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТопливоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТопливоL", typeof(IIS.SemyaDebilov.Топливо));
                }
            }
        }
    }
}
